Query map
vives-projectwerk-2021/backend pull request #25
Opened 2021-12-03 13:17 UTC by AaronVanV

Made a map with presets for get queries influx, so the frontend can, for example get the sensor "37003a000d5047394b373320" values of the week, and the values given will be per 30mins => ~336 values (*7 (4moistures,2temps, 1light))

works in postman, frontend doesn't request with queries yet, so shouldn't change functionality

2021-12-03 15:41 UTC, noahdebaere requested changes
Looks good, maybe delete the first start: -1h in the deviceRoute.js file (line 20)?

2021-12-03 17:03 UTC, AaronVanV commented
![image](https://user-images.githubusercontent.com/55448388/144642826-b93bc79a-0fe7-48af-8d4b-fe3200d07ffc.png)
Did you pull? it should be "default"

2021-12-04 09:06 UTC, noahdebaere reviewed
ok

2021-12-04 09:07 UTC, noahdebaere approved these changes

2021-12-04 09:07 UTC, merged